# Generated by Django 3.0.8 on 2020-07-15 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200714_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
    ]
